window.GAMS_CONFIG = {
  API_BASE: '',
  AGENCY_NAME: 'Bishnoi Gas Services',
  ADMIN_USER: 'Naveen Bishnoi',
  DEFAULT_CUST_USER: 'customer',
  STORAGE_KEY: 'gams_data_v3',
  SESSION_KEY: 'gams_session',
  TOKEN_KEY: 'gams_token',
  DEFAULT_ADMIN_RECOVERY: 'BGS2006',
  SUPPORT: {
    customerCare: '9876543210',
    complaintHotline: '9876543211',
    emergencyLeak: '1906',
    agencyEmergency: '9876599999',
    whatsapp: '9876543210',
    email: 'support@bishnoigas.com',
    officeHours: '8:00 AM – 8:00 PM (Mon–Sun)',
    address: 'Main Road, Near City Center — Bishnoi Gas Services',
  },
  AGENCY_UPI: 'bishnoigas@oksbi',
  AGENCY_BANK: { name: 'State Bank of India', account: '123456789012', ifsc: 'SBIN0001234', holder: 'Bishnoi Gas Services' },
  AGENCY_GST: {
    gstin: '08AABCB1234A1Z5',
    pan: 'AABCB1234A',
    state: 'Rajasthan',
    stateCode: '08',
    hsn: '27111900',
    cin: 'U74999RJ2020PTC068420',
  },
  TRACKING_STEPS: [
    { key: 'placed', label: 'Order Placed', icon: 'fa-clipboard-list' },
    { key: 'confirmed', label: 'Confirmed', icon: 'fa-circle-check' },
    { key: 'ontheway', label: 'Out for Delivery', icon: 'fa-truck-fast' },
    { key: 'delivered', label: 'Delivered', icon: 'fa-house-circle-check' },
  ],
  TRACKING_ORDER: ['placed', 'confirmed', 'ontheway', 'delivered'],
};
